const block = (lines) => lines.join('\n');

const generalHelp = block([
    '*MathCourier Help*',
    '',
    'A math assistant bot for WhatsApp.',
    'Render formulas, plot 2D and 3D math, and solve symbolic or numeric problems from chat.',
    '',
    'Type `!command` followed by a space and the content you want to send.',
    '',
    '*Commands (use `!help <command>` for details)*',
    '- `!latex <content>` - render formulas, chemistry, or diagrams',
    '- `!plot <expression> [options]` - 2D and 3D plotting',
    '- `!solve <expression> [options]` - equations, calculus, linear algebra, ODEs, and PDEs',
    '- `!help [topic]` - show this menu or a focused help page',
    '',
    '*Inline Helpers* (use `!help <helpers>` for details)',
    '`deriv[...]`, `integ[...]`, `grad[...]`, `lap[...]`, `div[...]`, `curl[...]`',
    '',
    '*Options* (use `!help <option>` for details)',
    '`view`, `kind`, `camera`, `animate`, `vars`, `mode`, `phase`, `ic`, `bc`, `param`',
    '',
    '*Quick Syntax Rules*',
    '- Ranges use brackets: `key:[min, max]`',
    '- Scalar options use `key:value`',
    '- Grouped options use `key:{...}`',
    '- Semicolons separate equations: `!solve x + y = 5; x - y = 1`',
    '- Matrix rows also use semicolons: `[1, 2; 3, 4]`'
]);

const detailedHelp = {
    syntax: block([
        '*Syntax Basics*',
        '',
        'Commands take the form `!command body [options]`.',
        'Do not use parentheses after the command: `!plot y = sin(x)`, not `!plot(y = sin(x))`.',
        '',
        'Structured commands accept one main body followed by labeled options.',
        'Format: `!command <body> key:val key:[min, max] key:{...}`',
        '',
        '*Separators*',
        '- Use commas for list elements: `vars:{x, y}`',
        '- Use semicolons for complete equations or conditions: `ic:{x(0)=1; y(0)=0}`',
        '- Inside matrix literals, semicolons separate rows: `[1, 2; 3, 4]`',
        '',
        '*Examples*',
        '- `!latex \\frac{1}{2}`',
        '- `!plot y = sin(x) x:[-10, 10] y:[-2, 2]`',
        '- `!plot (cos(3*t), sin(2*t)) kind:parametric t:[0, 2*pi]`',
        '- `!solve x^2 - 5*x + 6 = 0`',
        '- `!solve det([1, 2; 3, 4])`'
    ]),

    latex: block([
        '*Unified Latex Rendering*',
        '',
        '*What to send:* `!latex <content>`',
        '*Inline form:* put `$$ ... $$` anywhere in a normal message.',
        '',
        '*Modes*',
        '- `mode:formula` - standard KaTeX / LaTeX rendering',
        '- `mode:chem` - chemfig rendering through QuickLaTeX',
        '- `mode:tikz` - TikZ or circuitikz rendering through QuickLaTeX',
        '- `\\ce{...}` chemistry notation stays in formula mode and renders locally through KaTeX/mhchem',
        '',
        '*Auto-detection when `mode:` is omitted*',
        '- `\\begin{tikzpicture}` or `\\tikz` routes to TikZ',
        '- `\\chemfig{...}` or `\\setchemfig` routes to chemfig',
        '- Everything else defaults to formula rendering',
        '',
        '*Examples*',
        '- `!latex \\int_0^\\infty e^{-x^2} \\, dx = \\frac{\\sqrt{\\pi}}{2}`',
        '- `!latex \\ce{CO2 + H2O <=> H2CO3}`',
        '- `!latex \\chemfig{H-O-H}`',
        '- `!latex \\begin{tikzpicture}\\draw (0,0) -- (2,1);\\end{tikzpicture}`',
        '- `!latex x^2 + y^2 = 1 mode:chem`',
        '- `!latex x^2 + y^2 = 1 mode:tikz`'
    ]),

    plot: block([
        '*2D And 3D Plotting*',
        '',
        '*What to send:* `!plot <expression> [options]`',
        'Inline helpers such as `deriv[...]` and `integ[...]` can appear inside the expression; see `!help helpers`.',
        '',
        '*Options*',
        '- `view:2d|3d` - rendering mode; default is 2d',
        '- `<var>:[min, max]` - sampling domain for any axis or parameter',
        '- `xlim:[min, max]`, `ylim:[min, max]`, `zlim:[min, max]` - display viewport (overrides axis range without changing sampling)',
        '- `camera:<axis>` or `camera:<axis><angle>` - animated camera rotation in 3D',
        '- `animate:<param>` - animate a named plot variable or sweep parameter in 2D or 3D',
        '- In 2D, `animate` either draws the graph progressively or re-evaluates it frame by frame when you sweep a free parameter',
        '- `kind:parametric`, `kind:polar`, `kind:vector` - 2D plot kinds',
        '- `kind:curve`, `kind:surface`, `kind:vector` - 3D plot kinds',
        '',
        '*Ambiguous tuples*',
        '- Bare tuples like `(y, -x)` are not guessed automatically.',
        '- Use `kind:parametric`, `kind:polar`, or `kind:vector` when the intent is not obvious.',
        '',
        '*Examples*',
        '- `!plot y = sin(x) x:[-10, 10] y:[-2, 2]`',
        '- `!plot y = sin(x) animate:x x:[-10, 10] y:[-2, 2]`',
        '- `!plot y = sin(x - t) animate:t x:[-10, 10] y:[-2, 2] t:[0, 2*pi]`',
        '- `!plot (cos(3*t), sin(2*t)) kind:parametric t:[0, 2*pi]`',
        '- `!plot r = 1 + cos(theta) kind:polar theta:[0, 2*pi]`',
        '- `!plot (-y, x) kind:vector x:[-5, 5] y:[-5, 5]`',
        '- `!plot (-y, x) kind:vector animate:x x:[-5, 5] y:[-5, 5]`',
        '- `!plot z = sin(x)*cos(y) view:3d x:[-3, 3] y:[-3, 3]`',
        '- `!plot z = sin(x)*cos(y) view:3d x:[-5, 5] y:[-5, 5] xlim:[-3, 3] ylim:[-3, 3]`',
        '- `!plot z = sin(x - t)*cos(y) view:3d animate:t x:[-3, 3] y:[-3, 3] t:[0, 2*pi]`'
    ]),

    solve: block([
        '*Unified Solve Command*',
        '',
        '*What to send:* `!solve <expression> [options]`',
        'Inline helpers such as `deriv[...]`, `integ[...]`, `grad[...]`, and `curl[...]` can be nested inside solve expressions.',
        '',
        '*Equations*',
        '- `!solve x^2 - 4 = 0`',
        '- `!solve x + y = 5; x - y = 1`',
        '- If you omit `=`, the expression is treated as `= 0` only when the solver route expects an equation.',
        '',
        '*Isolation*',
        '- `!solve PV = nRT vars:T`',
        '- `!solve E = m * c^2 vars:c`',
        '',
        '*Inequalities And Domains*',
        '- `!solve x^2 - 4 > 0`',
        '- `!solve sin(x) = 0 x:[0, 2*pi]`',
        '',
        '*Expression Modes*',
        '- `!solve x^2 - 5*x + 6 mode:factor`',
        '- `!solve (x-1)^3 mode:expand`',
        '- `!solve cos(x)^2 - sin(x)^2 mode:simplify`',
        '',
        '*Calculus*',
        '- `!solve deriv[x^3, x]`',
        '- `!solve integ[sin(x), x:[0, pi]]`',
        '- `!solve deriv[x^3, x] - integ[2*x, x] mode:simplify`',
        '- Helper signatures are documented in `!help deriv` and `!help integ`',
        '',
        '*Vector Ops*',
        '- `!solve grad[x^2*y*z, vars:{x, y, z}]`',
        '- `!solve div[(x^2, y^2, z^2), vars:{x, y, z}]`',
        '- `!solve curl[(-y, x, 0), vars:{x, y, z}]`',
        '- Inline vector-helper signatures are documented in `!help grad`, `!help lap`, `!help div`, and `!help curl`',
        '',
        '*Matrices*',
        '- `!solve [1, 2; 3, 4] * [2, 0; 1, 2]`',
        '- `!solve det([1, 2; 3, 4])`',
        '- `!solve det([x, 1; 2, x]) = 0`',
        '',
        '*ODEs And PDEs*',
        '- `!solve dy/dx = -y ic:{y(0)=1} x:[-5, 5]`',
        '- `!solve du/dt = d2u/dx2 ic:{u(x,0)=sin(x)} bc:{u(0,t)=0; u(pi,t)=0} x:[0, pi] t:[0, 2]`',
        '',
        '*Ambiguity Rules*',
        '- Bare tuples like `(-y, x, 0)` are ambiguous on their own. Wrap them in a helper such as `curl[...]` or `div[...]`.'
    ]),

    helpers: block([
        '*Inline Helpers*',
        '',
        'Use helpers inside `!plot` and `!solve` when you want a symbolic subexpression instead of a separate command.',
        '',
        '*Helper pages*',
        '- `!help deriv` - derivative arguments and implicit differentiation',
        '- `!help integ` - integrals, bounds, and field-integral arguments',
        '- `!help grad` - gradient helper arguments',
        '- `!help lap` - Laplacian helper arguments',
        '- `!help div` - divergence helper arguments',
        '- `!help curl` - curl helper arguments',
        '',
        '*Main syntax families*',
        '- `deriv[x^3, x]`',
        '- `deriv[x^2 + y^2 = 4, dep:y, x]`',
        '- `integ[x^2 + y^2, x:[0, 1], y:[0, 2]]`',
        '- `grad("x^2*y*z", "vars:{x, y, z}")`',
        '- `curl("(-y, x, 0)", "vars:{x, y, z}")`',
        '',
        '*Rules*',
        '- `deriv` and `integ` use bracket-style arguments separated by commas',
        '- `grad`, `lap`, `div`, and `curl` take an expression first, then optionally `vars:{...}` when you want explicit coordinates',
        '- Vector fields are written as tuples such as `"(-y, x)"` or `"(x^2, y^2, z^2)"`',
        '',
        '*Quoted forms also work when needed*',
        '- `deriv("x^3", "x")`',
        '- `integ("sin(t)", "t:[0, x]")`',
        '',
        '*Good places to use them*',
        '- `!plot y = deriv[x^2 + y^2 = 4, dep:y, x]`',
        '- `!solve deriv[x^3, x] - 12 = 0`',
        '- `!solve integ[t^2, t:[0, x]] = 9 vars:x`'
    ]),

    deriv: block([
        '*deriv Helper*',
        '',
        'Computes ordinary, partial, mixed, or implicit derivatives inside another expression.',
        '',
        '*Argument patterns*',
        '- `deriv[expr, x]` - first derivative with respect to `x`',
        '- `deriv[expr, vars:{x:2}]` - second derivative with respect to `x`',
        '- `deriv[expr, vars:{x:2, y}]` - mixed partial derivative',
        '- `deriv[equation, dep:y, x]` - implicit derivative `dy/dx`',
        '- `deriv[expr, at:{x:1, y:2}]` - evaluate the derivative at a point in numeric contexts',
        '',
        '*Arguments*',
        '- First argument: the expression or equation to differentiate',
        '- Variable selector: either a bare variable like `x` or `vars:{...}`',
        '- Optional `dep:<var>`: marks the dependent variable for implicit differentiation',
        '- Optional `at:{name:value, ...}`: substitutes values after differentiating',
        '- If you omit the variable selector, `deriv` tries to infer one independent variable',
        '',
        '*Examples*',
        '- `deriv[x^3, x]`',
        '- `deriv[x^3*y^2, vars:{x:2, y}]`',
        '- `deriv[x^2 + y^2 = 4, dep:y, x]`',
        '- `!solve deriv[x^3, x] - 12 = 0`',
        '- `!plot y = deriv[x^2 + y^2 = 4, dep:y, x]`',
        '',
        '*Also accepted*',
        '- `deriv("x^3", "x")`',
        '- `deriv("x^3*y^2", "vars:{x:2, y}")`'
    ]),

    integ: block([
        '*integ Helper*',
        '',
        'Handles antiderivatives, definite integrals, and field integrals inside another expression.',
        '',
        '*Argument patterns*',
        '- `integ[expr, x]` - integrate with respect to `x`',
        '- `integ[expr, x:[0, pi]]` - one-variable definite integral',
        '- `integ[expr, x:[0, 1], y:[0, 2]]` - labeled multivariable definite integral',
        '- `integ[field, kind:line, param:{...}, t:[a, b]]` - line integral',
        '- `integ[field, kind:surface, param:{...}, u:[...], v:[...]]` - surface integral',
        '- `integ[expr, kind:volume, x:[...], y:[...], z:[...]]` - volume integral',
        '',
        '*Arguments*',
        '- First argument: a scalar expression or a vector field',
        '- Variable selector: a bare variable like `x` or `vars:{x, y}` when no explicit bounds are given',
        '- Range arguments: `x:[a, b]`, `y:[c, d]`, and so on',
        '- Optional `kind:line|surface|volume`: switches to field-integral modes',
        '- Optional `param:{...}`: parametrization for line or surface integrals',
        '',
        '*Examples*',
        '- `integ[sin(x), x]`',
        '- `integ[sin(x), x:[0, pi]]`',
        '- `integ[x^2 + y^2, x:[0, 1], y:[0, 2]]`',
        '- `integ[(-y, x), kind:line, param:{cos(t), sin(t)}, t:[0, 2*pi]]`',
        '- `integ[(0, 0, z), kind:surface, param:{sin(u)*cos(v), sin(u)*sin(v), cos(u)}, u:[0, pi], v:[0, 2*pi]]`',
        '- `integ[x*y*z, kind:volume, x:[0, 1], y:[0, 2], z:[0, 3]]`',
        '',
        '*Also accepted*',
        '- `integ("sin(t)", "t:[0, x]")`',
        '- `integ("x^2 + y^2", "x:[0, 1]", "y:[0, 2]")`'
    ]),

    grad: block([
        '*grad Helper*',
        '',
        'Computes the gradient of a scalar field.',
        '',
        '*Argument pattern*',
        '- `grad[expr]`',
        '- `grad[expr, vars:{x, y}]`',
        '- `grad[expr, vars:{x, y, z}]`',
        '',
        '*Arguments*',
        '- First argument: a scalar field such as `"x^2 + y^2"`',
        '- Optional `vars:{...}`: explicitly names 1 to 3 coordinate variables',
        '- If `vars:{...}` is omitted, `grad` tries to infer the variables from the expression',
        '',
        '*Examples*',
        '- `grad[x^2 + y^2]`',
        '- `grad[x^2*y*z, vars:{x, y, z}]`',
        '- `!solve grad[x^2*y*z, vars:{x, y, z}]`'
    ]),

    lap: block([
        '*lap Helper*',
        '',
        'Computes the Laplacian of a scalar field.',
        '',
        '*Argument pattern*',
        '- `lap[expr]`',
        '- `lap[expr, vars:{x, y}]`',
        '- `lap[expr, vars:{x, y, z}]`',
        '',
        '*Arguments*',
        '- First argument: a scalar field',
        '- Optional `vars:{...}`: explicitly names 1 to 3 coordinate variables',
        '- If `vars:{...}` is omitted, `lap` tries to infer the variables from the expression',
        '',
        '*Examples*',
        '- `lap[x^2 + y^2]`',
        '- `lap[x^2 + y^2 + z^2, vars:{x, y, z}]`',
        '- `!solve lap[x^2 + y^2, vars:{x, y}]`'
    ]),

    div: block([
        '*div Helper*',
        '',
        'Computes the divergence of a 2D or 3D vector field.',
        '',
        '*Argument pattern*',
        '- `div[(Fx, Fy)]`',
        '- `div[(Fx, Fy), vars:{x, y}]`',
        '- `div[(Fx, Fy, Fz), vars:{x, y, z}]`',
        '',
        '*Arguments*',
        '- First argument: a vector field written as a tuple',
        '- Optional `vars:{...}`: coordinate variables matching the vector-field dimension',
        '- If `vars:{...}` is omitted, `div` tries to infer the variables from the vector field',
        '',
        '*Examples*',
        '- `div[(x^2, y^2)]`',
        '- `div[(x^2, y^2, z^2), vars:{x, y, z}]`',
        '- `!solve div[(x^2, y^2, z^2), vars:{x, y, z}]`'
    ]),

    curl: block([
        '*curl Helper*',
        '',
        'Computes the curl of a 2D or 3D vector field.',
        '',
        '*Argument pattern*',
        '- `curl[(Fx, Fy)]`',
        '- `curl[(Fx, Fy), vars:{x, y}]`',
        '- `curl[(Fx, Fy, Fz), vars:{x, y, z}]`',
        '',
        '*Arguments*',
        '- First argument: a vector field written as a tuple',
        '- Optional `vars:{...}`: coordinate variables matching the vector-field dimension',
        '- If `vars:{...}` is omitted, `curl` tries to infer the variables from the vector field',
        '- In 2D, the result is a scalar curl; in 3D, the result is a vector curl',
        '',
        '*Examples*',
        '- `curl[(-y, x)]`',
        '- `curl[(-y, x, 0), vars:{x, y, z}]`',
        '- `!solve curl[(-y, x, 0), vars:{x, y, z}]`'
    ]),

    view: block([
        '*view - Rendering Dimension*',
        '',
        'Controls whether output is rendered in 2D or 3D.',
        'Format: `view:2d` or `view:3d`',
        '',
        '*Values*',
        '- `view:2d` - 2D rendering; default for `!plot`; supports `animate`',
        '- `view:3d` - 3D rendering; enables 3D plot kinds, `camera`, and `animate`',
        '',
        '*Used by*: `!plot`, `!solve` when routing to PDE rendering'
    ]),

    camera: block([
        '*camera - Animated Camera Rotation*',
        '',
        'Rotates the camera around a 3D scene and produces an animated output.',
        'Format: `camera:<axis>` or `camera:<axis><angle>`',
        '',
        '*Values*',
        '- `<axis>` - `x`, `y`, or `z`',
        '- `<angle>` - optional integer degrees, such as `360` or `180`',
        '- Without `<angle>` the camera swings back and forth',
        '',
        '*Used by*: `!plot view:3d`, `!solve` when routing to PDE rendering'
    ]),

    kind: block([
        '*kind - Plot Or Integral Type*',
        '',
        'Specifies the type of plot or field integral.',
        'Format: `kind:<type>`',
        '',
        '*For `!plot` in 2D*',
        '- `kind:parametric` - parametric curve',
        '- `kind:polar` - polar curve',
        '- `kind:vector` - vector field',
        '',
        '*For `!plot view:3d`*',
        '- `kind:curve` - parametric 3D curve',
        '- `kind:surface` - parametric 3D surface',
        '- `kind:vector` - 3D vector field',
        '',
        '*For `!solve` field integrals*',
        '- `kind:line` - line integral; requires `param:{...}` and one parameter range',
        '- `kind:surface` - surface integral; requires `param:{...}` and two parameter ranges',
        '- `kind:volume` - volume integral; provide a range for each integration variable',
        '',
        '*Used by*: `!plot`, `!solve`'
    ]),

    animate: block([
        '*animate - Parameter Evolution Animation*',
        '',
        'Animates a named plot variable or free parameter and produces a frame-by-frame animation.',
        'Format: `animate:<param>`',
        '',
        '*Rules*',
        '- `<param>` must be a variable name that appears in the expression',
        '- In 2D, if `<param>` is the plotted axis or curve parameter, the graph is drawn progressively across that range',
        '- In 2D or 3D, if `<param>` is a free sweep parameter, the expression is re-evaluated frame by frame',
        '- A matching range is recommended for free sweeps; if omitted, the sweep falls back to `0` through `2*pi`',
        '',
        '*Examples*',
        '- `!plot y = sin(x) animate:x x:[-10, 10] y:[-2, 2]`',
        '- `!plot y = sin(x - t) animate:t x:[-10, 10] y:[-2, 2] t:[0, 2*pi]`',
        '- `!plot z = sin(x - t)*cos(y) view:3d animate:t x:[-3, 3] y:[-3, 3] t:[0, 2*pi]`'
    ]),

    vars: block([
        '*vars - Variable Specification*',
        '',
        'Specifies which variable or variables a solve-related operation should use.',
        '',
        '*Forms*',
        '- `vars:x` - single variable',
        '- `vars:{x, y}` - multiple variables',
        '- `vars:{x:2}` - variable with order for differentiation',
        '- `vars:{x:2, y}` - mixed differentiation orders',
        '',
        '*Within `!solve`, `vars` is used for*',
        '- Variable isolation: `!solve PV = nRT vars:T`',
        '- Differentiation and integration helpers when auto-detection is unclear',
        '- Vector operators when you want explicit coordinate variables',
        '',
        '*Used by*: `!solve`'
    ]),

    mode: block([
        '*mode - Router Or Solving Strategy*',
        '',
        'The meaning of `mode:` depends on the command.',
        '',
        '*For `!latex`*',
        '- `mode:formula` - standard KaTeX / LaTeX',
        '- `mode:chem` - chemfig rendering',
        '- `mode:tikz` - TikZ rendering',
        '',
        '*For `!solve` expression modes*',
        '- `mode:simplify` - evaluate and simplify an expression',
        '- `mode:factor` - factor an expression',
        '- `mode:expand` - expand an expression',
        '',
        '*For differential-equation solving*',
        '- `mode:sym` - symbolic only',
        '- `mode:num` - numerical only',
        '- `mode:hybrid` - symbolic first, numerical fallback',
        '',
        '*Rules*',
        '- `mode:sym`, `mode:num`, and `mode:hybrid` only apply when `!solve` auto-detects an ODE or PDE.',
        '',
        '*Used by*: `!latex`, `!solve`'
    ]),

    phase: block([
        '*phase - Phase Portrait*',
        '',
        'Plots a phase portrait instead of a time-domain ODE solution.',
        'Format: `phase:{var1, var2}`',
        '',
        '*Rules*',
        '- Must contain exactly two distinct variable names',
        '- Forces numerical solving',
        '- Best used for autonomous ODE systems',
        '',
        '*Used by*: `!solve` when routing to ODE solving'
    ]),

    ic: block([
        '*ic - Initial Conditions*',
        '',
        'Specifies initial conditions for a differential equation.',
        'Format: `ic:{condition}` or `ic:{cond1; cond2; ...}`',
        '',
        '*Examples*',
        '- `ic:{y(0)=1}`',
        "- `ic:{y(0)=1; y''(0)=0}`",
        '- `ic:{x(0)=1; y(0)=0}`',
        '- `ic:{u(x,0)=sin(x)}`',
        '',
        '*Used by*: `!solve` when routing to ODE or PDE solving'
    ]),

    bc: block([
        '*bc - Boundary Conditions*',
        '',
        'Specifies spatial boundary conditions for a PDE.',
        'Format: `bc:{cond1; cond2}`',
        '',
        '*Example*',
        '- `bc:{u(0,t)=0; u(pi,t)=0}`',
        '',
        '*Used by*: `!solve` when routing to PDE solving'
    ]),

    param: block([
        '*param - Parametric Curve Or Surface*',
        '',
        'Defines the path or surface for field integrals.',
        'Format: `param:{fx, fy}` or `param:{fx, fy, fz}`',
        '',
        '*Examples*',
        '- `!solve integ[(-y, x), kind:line, param:{cos(t), sin(t)}, t:[0, 2*pi]]`',
        '- `!solve integ[(0,0,z), kind:surface, param:{sin(u)*cos(v), sin(u)*sin(v), cos(u)}, u:[0, pi], v:[0, 2*pi]]`',
        '',
        '*Used by*: `!solve` field-integral helpers'
    ]),

    xlim: block([
        '*xlim / ylim / zlim - Display Viewport*',
        '',
        'Clamps the visible axis range without changing the sampling domain.',
        'Format: `xlim:[min, max]`  `ylim:[min, max]`  `zlim:[min, max]`',
        '',
        '*Difference from domain ranges*',
        '- `x:[min, max]` controls where the math is *evaluated* (sampling domain)',
        '- `xlim:[min, max]` controls what the *viewer sees* (camera / axis range)',
        '- You can sample a wider area than you display, or zoom in without re-sampling.',
        '',
        '*Rules*',
        '- All three are optional and independent of each other.',
        '- `zlim` is only meaningful for `view:3d`.',
        '- When omitted the viewport defaults to the sampling domain.',
        '',
        '*Examples*',
        '- `!plot z = sin(x)*cos(y) view:3d x:[-5,5] y:[-5,5] xlim:[-3,3] ylim:[-3,3]`',
        '- `!plot y = sin(x) x:[-20, 20] xlim:[-5, 5] ylim:[-2, 2]`',
        '',
        '*Used by*: `!plot`'
    ])
};

function isHelpText(body = '') {
    const trimmed = String(body || '').trim();
    if (!trimmed) {
        return false;
    }

    if (trimmed === generalHelp) {
        return true;
    }

    return Object.values(detailedHelp).includes(trimmed);
}

function getHelp(cmd = '') {
    const normalized = String(cmd || '').trim().toLowerCase().replace(/^!/, '');
    if (!normalized) {
        return generalHelp;
    }

    const aliases = {
        '$$': 'latex',
        deriv: 'deriv',
        integ: 'integ',
        derivative: 'deriv',
        derivatives: 'deriv',
        integral: 'integ',
        integrals: 'integ',
        helper: 'helpers',
        helpers: 'helpers',
        basics: 'syntax',
        format: 'syntax',
        ranges: 'syntax',
        domains: 'syntax',
        '2d': 'view',
        '3d': 'view',
        animation: 'animate',
        parameter: 'param',
        parameters: 'param',
        initial: 'ic',
        boundary: 'bc',
        variable: 'vars',
        variables: 'vars',
        options: 'syntax',
        ylim: 'xlim',
        zlim: 'xlim',
        viewport: 'xlim',
        limits: 'xlim',
        lim: 'xlim'
    };

    const key = aliases[normalized] || normalized;
    if (detailedHelp[key]) {
        return detailedHelp[key];
    }

    return `*MathCourier* - Command not found: !${normalized}\n\nType \`!help\` to see all available commands.`;
}

getHelp.isHelpText = isHelpText;

module.exports = getHelp;
