const helpText = [
    '*LaTeX Render Bot Help Menu*',
    '',
    'Welcome to the LaTeX and Graphing Bot. Here are the commands you can use to render math, chemistry, diagrams, and plots.',
    '',
    '--------------------------',
    '',
    '*1. LaTeX / Mathematics*',
    '- *Command:* `!latex <formula>` (or `!tex`)',
    '  _Example:_ `!latex \\int_0^\\infty e^{-x^2} dx = \\frac{\\sqrt{\\pi}}{2}`',
    '- *Inline Blocks:* Wrap formulas in `$$` anywhere in your text.',
    '  _Example:_ `The solution to x^2 = 4 is $$x = \\pm 2$$`',
    '',
    '*2. Symbolic Calculus*',
    '- *Differentiation:* `!diff <expression> [variables/orders]`',
    '  _Examples:_ `!diff x^2 * sin(x)` or `!diff x^3 * y^2, x, 2, y`',
    '- *Integration:* `!int <expression> [variables/limits]`',
    '  _Examples:_ `!int x^2` or `!int sin(x) x 0 pi` or `!int x^2 + y^2, x, 0, 1, y, 0, 2`',
    '- *Vector and Multivariable Field Integrals:*',
    '  _Examples:_ `!int line (-y, x) path (cos(t), sin(t)) [0, 2*pi]`',
    '  `!int surface (0, 0, z) surface (sin(u)*cos(v), sin(u)*sin(v), cos(u)) [0, pi] [0, 2*pi]`',
    '  `!int volume x*y*z [0, 1] [0, 2] [0, 3]`',
    '',
    '*3. Chemistry Structures*',
    '- *Command:* `!chem <formula>` (or `!chemfig`)',
    '  _Example:_ `!chem \\chemfig{A-B*6(=-=-=-)}`',
    '',
    '*4. TikZ and Circuit Diagrams*',
    '- *Command:* `!tikz <tikz/circuitikz code>`',
    '  _Example:_',
    '  `!tikz`',
    '  `\\draw[thick, fill=blue!10] (0,0) circle (1.5);`',
    '  `\\node at (0,0) {Hello!};`',
    '  _Or draw a circuit:_',
    '  `\\draw (0,0) to[R, l=$R$] (2,0);`',
    '',
    '*5. Function and Equation Plotting*',
    '- *Command:* `!plot <expression(s)> [xRange] [yRange]`',
    '  _Plots lines, curves, vector fields, derivatives, integrals, and multiple overlaid curves on a square coordinate grid._',
    '',
    '  *a) Explicit Functions and Multi-Plotting:*',
    '  - `!plot y = x^2 - 4`',
    '  - `!plot y = sin(x), y = cos(x), y = x/5 [-10, 10] [-2, 2]`',
    '  - `!plot sin(x) * cos(x/2) [-10, 10] [-2, 2]`',
    '',
    '  *b) Implicit Equations:*',
    '  - `!plot x^2 + y^2 = 9`',
    '  - `!plot y^2 = x^3 - x [-2, 2] [-2, 2]`',
    '',
    '  *c) Vector Fields:*',
    '  - `!plot v(x,y) = (-y, x) [-5, 5] [-5, 5]`',
    '  - `!plot (-y, x) [-5, 5] [-5, 5]`',
    '',
    '  *d) Derivatives:*',
    '  - `!plot y = deriv("x^3", "x", x) [-3, 3] [-10, 10]`',
    '',
    '  *e) Definite Integrals:*',
    '  - `!plot y = integ("sin(t)", "t", 0, x) [-10, 10] [-3, 3]`',
    '',
    '  *f) Inline Vector Operators:*',
    '  - `!plot y = lap("x^3", x) [-3, 3] [-20, 20]`',
    '  - `!plot v(x,y) = (gradx("x^2 + y^2", x, y), grady("x^2 + y^2", x, y)) [-3, 3] [-3, 3]`',
    '',
    '*6. 3D Surface and Curve Plotting*',
    '- *Command:* `!plot3d [-a|-a360] <expression> [xRange] [yRange] [zRange]`',
    '  _Renders a premium 3D explicit surface or 3D parametric curve card preview using Plotly.js._',
    '  _Use `-a` for a slower front-facing swing animation, or `-a360` for a full orbit around the plot._',
    '  - `!plot3d z = sin(x) * cos(y) [-3, 3] [-3, 3]`',
    '  - `!plot3d -a z = sin(x) * cos(y) [-3, 3] [-3, 3]`',
    '  - `!plot3d -a360 x^2 + y^2 + z^2 = 1 [-6, 6] [-6, 6]`',
    '  - `!plot3d (sin(t), cos(t), t) [0, 6*pi]`',
    '  - `!plot3d z = lap("x^2 + y^2", x, y) [-3, 3] [-3, 3] [0, 8]`',
    '  - `!plot3d F(x,y,z) = (-y, x, z/2) [-4, 4] [-4, 4] [-4, 4]`',
    '  - `!plot3d (-y, x, z/2) [-4, 4] [-4, 4] [-4, 4]`',
    '',
    '*7. Equation Solver*',
    '- *Command:* `!solve <equation(s)>`',
    '  _Solves equations or linear systems and returns a styled card with symbolic roots or numerical convergence steps._',
    '  - `!solve x^2 - 5x + 6 = 0`',
    '  - `!solve cos(x) - x = 0`',
    '  - `!solve x + y = 5; x - y = 1`',
    '',
    '*8. Differential Equations Solver*',
    '- *Command:* `!ode [options] <equation(s)>, <initial condition(s)> [xRange] [yRange]`',
    '  _Solves first-order, higher-order ODEs, and systems of ODEs symbolically or numerically, rendering the trajectory plot._',
    '  - `!ode dy/dx = -y, y(0) = 1`',
    '  - `!ode -s y\'\' + y = 0, y(0)=1, y\'(0)=0`',
    '  - `!ode -n dx/dt = -y; dy/dt = x, x(0)=1, y(0)=0 [-5, 5]`',
    '',
    '*9. Vector Differential Operators*',
    '- *Gradient:* `!grad <scalar_field> [, var1, var2, var3]`',
    '  _Computes the symbolic gradient of a scalar field in 2D or 3D._',
    '  - `!grad x^2 * y * z`',
    '  - `!grad x^2 + y^2, x, y`',
    '- *Laplacian:* `!lap <scalar_field> [, var1, var2, var3]`',
    '  _Computes the symbolic Laplacian of a scalar field in 1D, 2D, or 3D._',
    '  - `!lap x^2 + y^2, x, y`',
    '  - `!lap x^3`',
    '- *Divergence:* `!div <vector_field> [, var1, var2, var3]`',
    '  _Computes the symbolic divergence of a 2D or 3D vector field._',
    '  - `!div (x^2, y^2)`',
    '  - `!div (x^2, y^2, z^2)`',
    '- *Curl:* `!curl <vector_field> [, var1, var2, var3]`',
    '  _Computes the symbolic curl of a 2D or 3D vector field._',
    '  - `!curl (-y, x)`',
    '  - `!curl (-y, x, 0)`',
    '- *Inline Helpers:* `grad(...)`, `lap(...)`, `div(...)`, `curl(...)`, `gradx(...)`, `grady(...)`, `gradz(...)`, `curlx(...)`, `curly(...)`, `curlz(...)`',
    '  _These work inside local mathjs-evaluated expressions such as `!plot` and scalar `!plot3d` surfaces._',
    '',
    '*10. Symbolic Variable Rearrangement*',
    '- *Command:* `!desp <equation> for <variable>`',
    '  _Symbolically rearranges and isolates the target variable in the given equation._',
    '  - `!desp E = m * c^2 for c`',
    '  - `!desp PV = n*R*T for T`',
    '',
    '--------------------------',
    '*Tip:* Wrap ranges in brackets `[min, max]`. One range defines X limits. Two ranges define X and Y limits. Three ranges in `!plot3d` define X, Y, and Z limits.'
].join('\n');

module.exports = helpText;
