const helpText = [
    '*LaTeX Render Bot Help Menu*',
    '',
    'Welcome to the LaTeX & Graphing Bot! Here are all the commands you can use to render math, chemistry, diagrams, and plots.',
    '',
    '──────────────────────────',
    '',
    '*1. LaTeX / Mathematics*',
    '• *Command:* `!latex <formula>` (or `!tex`)',
    '  _Example:_ `!latex \\int_0^\\infty e^{-x^2} dx = \\frac{\\sqrt{\\pi}}{2}`',
    '• *Inline Blocks:* Wrap formulas in `$$` anywhere in your text.',
    '  _Example:_ `The solution to $x^2=4$ is $$x = \\pm 2$$`',
    '',
    '*2. Symbolic Calculus*',
    '• *Differentiation:* `!diff <expression> [variable]`',
    '  _Example:_ `!diff x^2 * sin(x)` or `!diff u^3 - u y, u`',
    '• *Integration:* `!int <expression> [variable] [lower] [upper]`',
    '  _Example:_ `!int x^2` or `!int sin(x) x 0 pi`',
    '',
    '*3. Chemistry Structures*',
    '• *Command:* `!chem <formula>` (or `!chemfig`)',
    '  _Example:_ `!chem \\chemfig{A-B*6(=-=-=-)}`',
    '',
    '*4. TikZ & Circuit Diagrams*',
    '• *Command:* `!tikz <tikz/circuitikz code>`',
    '  _Example:_',
    '  `!tikz`',
    '  `\\draw[thick, fill=blue!10] (0,0) circle (1.5);`',
    '  `\\node at (0,0) {Hello!};`',
    '  _Or draw a circuit:_',
    '  `\\draw (0,0) to[R, l=$R$] (2,0);`',
    '',
    '*5. Function & Equation Plotting*',
    '• *Command:* `!plot <expression(s)> [xRange] [yRange]`',
    '  _Plots lines, curves, vector fields, derivatives, integrals, and multiple overlaid curves on a square coordinate grid._',
    '',
    '  *a) Explicit Functions & Multi-Plotting:*',
    '  • `!plot y = x^2 - 4`',
    '  • `!plot y = sin(x), y = cos(x), y = x/5 [-10, 10] [-2, 2]` (multi-curve overlay)',
    '  • `!plot sin(x) * cos(x/2) [-10, 10] [-2, 2]`',
    '',
    '  *b) Implicit Equations:*',
    '  • `!plot x^2 + y^2 = 9` (renders a circle)',
    '  • `!plot y^2 = x^3 - x [-2, 2] [-2, 2]`',
    '',
    '  *c) Vector Fields:*',
    '  • `!plot v(x,y) = (-y, x) [-5, 5] [-5, 5]`',
    '',
    '  *d) Derivatives:*',
    '  • `!plot y = deriv("x^3", "x", x) [-3, 3] [-10, 10]`',
    '',
    '  *e) Definite Integrals:*',
    '  • `!plot y = integ("sin(t)", "t", 0, x) [-10, 10] [-3, 3]`',
    '',
    '*6. Equation Solver*',
    '• *Command:* `!solve <equation(s)>`',
    '  _Solves equations or linear systems (returns a styled card with symbolic roots or numerical convergence steps)._',
    '  • `!solve x^2 - 5x + 6 = 0` (symbolic quadratic)',
    '  • `!solve cos(x) - x = 0` (numerical Newton-Raphson)',
    '  • `!solve x + y = 5; x - y = 1` (linear system)',
    '',
    '*7. Differential Equations Solver*',
    '• *Command:* `!ode [options] <equation(s)>, <initial condition(s)> [xRange] [yRange]`',
    '  _Solves first-order, higher-order ODEs, and systems of ODEs symbolically or numerically, rendering the trajectory plot._',
    '  • `!ode dy/dx = -y, y(0) = 1` (default hybrid solving)',
    '  • `!ode -s y\'\' + y = 0, y(0)=1, y\'(0)=0` (symbolic-only flag)',
    '  • `!ode -n dx/dt = -y; dy/dt = x, x(0)=1, y(0)=0 [-5, 5]` (numerical-only system)',
    '',
    '*8. Symbolic Variable Rearrangement*',
    '• *Command:* `!desp <equation> for <variable>`',
    '  _Symbolically rearranges and isolates the target variable in the given equation._',
    '  • `!desp E = m * c^2 for c` (isolates c)',
    '  • `!desp PV = n*R*T for T` (isolates T)',
    '',
    '──────────────────────────',
    '*Tip:* Wrap ranges in brackets `[min, max]`. If you specify one range, it defines the X-axis limits. If you specify two, they define the X and Y limits respectively.'
].join('\n');

module.exports = helpText;
